from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get("https://www.saucedemo.com/")
name = driver.find_element("id","user-name")
name.send_keys("standard_user")
time.sleep(2)
password = driver.find_element("id", "password")
password.send_keys("secret_sauce")
time.sleep(2)
login = driver.find_element("id", "login-button")
login.click()
time.sleep(2)
item1 = driver.find_element("id", "add-to-cart-sauce-labs-backpack")
item1.click()
time.sleep(2)
item2 = driver.find_element("id", "add-to-cart-sauce-labs-bike-light")
item2.click()
time.sleep(2)
item3 = driver.find_element("id", "add-to-cart-sauce-labs-bolt-t-shirt")
item3.click()
time.sleep(2)
item4 = driver.find_element("xpath", "//*[@id=\"item_4_title_link\"]/div")
item4.click()
time.sleep(2)
cart = driver.find_element("id", "shopping_cart_container")
cart.click()
time.sleep(2)
checkout = driver.find_element("id", "checkout")
checkout.click()
time.sleep(2)
first_name = driver.find_element("id", "first-name")
first_name.send_keys("Eden")
time.sleep(2)
last_name = driver.find_element("id", "last-name")
last_name.send_keys("Yeong")
time.sleep(2)
zip = driver.find_element("id", "postal-code")
zip.send_keys("123457")
time.sleep(2)
cont = driver.find_element("id", "continue")
cont.click()
time.sleep(2)
fin = driver.find_element("id", "finish")
fin.click()
time.sleep(2)
home = driver.find_element("id", "back-to-products")
home.click()
time.sleep(10)