import telebot
from telebot import types
token = "6238979933:AAHkDBK_I7HkmLUMlCzcqMWPJnF60TxwNLc"
bot = telebot.TeleBot(token)
@bot.message_handler(commands=["start"])
def start(message):
    keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
    btn1 = types.KeyboardButton("О группе")
    btn2 = types.KeyboardButton("Дискография")
    keyboard.add(btn1, btn2)
    bot.send_message(message.chat.id, "Бот посвящен группе Ateez", reply_markup = keyboard)
@bot.message_handler(commands=["about"])
def about(message):
    bot.send_message(message.chat.id, "Бот создан @rrtouwe, 14 марта 2023")
@bot.message_handler(content_types=['text'])
def answer(message):
    if message.text == "О группе":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        bot.send_message(message.chat.id, "Выберите интересующий раздел", reply_markup = keyboard)
    if message.text == "Дискография":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn6 = types.KeyboardButton("Назад")
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        keyboard.add(btn6, btn7, btn8)
        bot.send_message(message.chat.id, "Выберите раздел", reply_markup = keyboard)
    if message.text == "Корейские альбомы":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btnn = types.KeyboardButton("TREASURE EP.1 : All To Zero")
        btnm = types.KeyboardButton("TREASURE EP.2: Zero To One")
        btn14 = types.KeyboardButton("TREASURE EP.3 : One To All")
        btn15 = types.KeyboardButton("TREASURE EP.FIN : All To Action")
        btn17 = types.KeyboardButton("TREASURE EPILOGUE : Action To Answer")
        btn19 = types.KeyboardButton("ZERO : FEVER Part.1")
        btn20 = types.KeyboardButton("ZERO : FEVER Part.2")
        btn21 = types.KeyboardButton("ZERO : FEVER Part.3")
        btn22 = types.KeyboardButton("ZERO : FEVER EPILOGUE")
        btn23 = types.KeyboardButton("THE WORLD EP.1 : MOVEMENT")
        btn24 = types.KeyboardButton("SPIN OFF : FROM THE WITNESS")
        keyboard.add(btnn, btnm, btn14, btn15, btn17, btn19, btn20, btn21, btn22, btn23, btn24)
        bot.send_message(message.chat.id, "Выберите раздел", reply_markup = keyboard)
    if message.text == "TREASURE EP.1 : All To Zero":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trep1.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: \n1. Intro : Long Journey \n2. 해적왕(Pirate King) TITLE \n3. Treasure TITLE \n4. Twilight \n5. Stay \n6. My Way", reply_markup = keyboard)
    if message.text == "TREASURE EP.2: Zero To One":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trep2.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: \n1. HALA HALA (Hearts Awakened, Live Alive) \n2. Say My Name TITLE \n3. Desire \n4. Light \n5. Promise \n6. From", reply_markup = keyboard)
    if message.text == "TREASURE EP.3 : One To All":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trep3.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1. UTOPIA 2. ILLUSION TITLE 3. Crescent 4. WAVE TITLE 5. AURORA 6. Dancing Like Butterfly Wings", reply_markup = keyboard)
    if message.text == "TREASURE EP.FIN : All To Action":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trepfin.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1. End of the Beginning 2. WONDERLAND TITLE 3. Dazzling Light 4. 안개 5. Precious (Overture) 6. WIN 7. If Without You 8. 친구 (THANK U) 9. Sunrise 10. 걸어가고 있어 11. Beginning of the End", reply_markup = keyboard)
    if message.text == "TREASURE EPILOGUE : Action To Answer":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trepil.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1. Answer TITLE 2. 지평선 (Horizon) 3. Star 1117 4. Precious 5. Outro : Long Journey", reply_markup = keyboard)
    if message.text == "ZERO : FEVER Part.1":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("fevp1.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1. Dear Diary : 2016.07.29 2. FEVER 3. THANXX TITLE 4. 춤을 춰 (TO THE BEAT) 5. INCEPTION TITLE 6. Good Lil Boy 7. One Day At A Time", reply_markup = keyboard)
    if message.text == "ZERO : FEVER Part.2":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("fevp2.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек_лист: 1. 불놀이야 (I'm The One) TITLE 2. 선도부 (The Leaders) 3. Time Of Love 4. Take Me Home 5. Celebrate 6. Take Me Home (English ver.) 7. I'm The One (HEAT-TOPPING ver.)", reply_markup = keyboard)
    if message.text == "ZERO : FEVER Part.3":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("fevp3.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек_лист: 1. Eternal Sunshine TITLE 2. Feeling Like I Do 3. Deja Vu TITLE 4. ROCKY 5. All About You 6. 밤하늘 (Not Too Late)", reply_markup = keyboard)
    if message.text == "ZERO : FEVER EPILOGUE":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("fevepil.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек_лист: 1. 야간비행 (Turbulence) TITLE 2. Be With You 3. The Letter 4. Still Here (Korean Ver.) 5. Better (Korean Ver.) 6. 멋 (The Real) (흥 : 興 Ver.) TITLE 7. WAVE (Overture) 8. WONDERLAND (Symphony No.9 “From The Wonderland”) 9. Answer (Ode to Joy) (Feat. LA POEM) 10. Outro : Over the Horizon", reply_markup = keyboard)
    if message.text == "THE WORLD EP.1 : MOVEMENT":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("movement.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек_лист: 1. PROPAGANDA 2. Sector 1 3. Cyberpunk 4. Guerrilla TITLE 5. The Ring 6. WDIG (Where Do I Go) 7. New World", reply_markup = keyboard)
    if message.text == "SPIN OFF : FROM THE WITNESS":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("spinoff.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек_лист: 1. HALAZIA TITLE 2. WIN (June One of Glen Check Remix) 3. I’m The One (Eden-ary Remix) 4. Take Me Home (IDIOTAPE Remix) 5. Outro : Blue Bird", reply_markup = keyboard)
    
    if message.text == "Японские альбомы":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn10 = types.KeyboardButton("TREASURE EP.EXTRA : SHIFT THE MAP")
        btn11 = types.KeyboardButton("TREASURE EP.Map To Answer")
        btn12 = types.KeyboardButton("Into the A to Z")
        btn13 = types.KeyboardButton("Dreamers")
        btn30 = types.KeyboardButton("BEYOND : ZERO")
        btn31 = types.KeyboardButton("THE WORLD EP.PARADIGM")
        btn32 = types.KeyboardButton("Limitless")
        keyboard.add(btn10, btn11, btn12, btn13, btn30, btn31, btn32)
        bot.send_message(message.chat.id, "Выберите раздел", reply_markup = keyboard)
    if message.text == "Limitless":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("limitless.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1. Limitless 2. Diamond 3. Limitless (Instrumental) 4. Diamond (Instrumental)", reply_markup = keyboard)
    if message.text == "BEYOND : ZERO":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("bzero.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1.INTRO [BEYOND : ZERO] 2.Deja Vu (Japanese Ver.) 3.ROCKY (Boxers Ver.) 4.The King 5.夜間飛行 야간비행 (Turbulence) (Japanese Ver.) 6.Take Me Home (Japanese Ver.) 7.Fireworks (I'm The One) (Japanese Ver.)", reply_markup = keyboard)
    if message.text == "THE WORLD EP.PARADIGM":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("paradigm.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1.Intro : Siren 2.Paradigm 3.Cyberpunk (Japanese Ver.) 4.Guerrilla (Flag Ver.) 5.New World (Japanese Ver.) 6.Outro : Liberty", reply_markup = keyboard)
    if message.text == "Dreamers":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("dream.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1.Dreamers 2.Blue Summer 3.Still Here (Acoustic Ver.) 4.Dreamers (Instrumental)", reply_markup = keyboard)
    if message.text == "TREASURE EP.EXTRA : SHIFT THE MAP":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trepex.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1.Hearts Awakened, Live Alive (Expression Revisited) 2.HALA HALA (Traditional Treatment Mix) 3.Pirate King (Overload Mix) 4.Treasure (Soothing Harmonies Mix) 5.UTOPIA (Japanese Ver.) 6.Say My Name (Flavor of Latin with Juwon Park) 7.ILLUSION (Chillin' With BUDDY Mix) 8.WAVE (Ollounder's Bold Dynamics Mix) 9.AURORA (Japanese Ver.) 10.Twilight (Classic BUDDY Mix) 11.Promise (Notation from Señor Juwon Park)", reply_markup = keyboard)
    if message.text == "TREASURE EP.Map To Answer":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("trepmap.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1. Declaration 2. Answer (Japanese Ver.) 3. Better TITLE 4. WONDERLAND (SEAN OH's Skrt Mix) 5. Sunrise (Atmospheric Mix by SPACECOWBOY) 6. Star 1117 (BUDDY's Melodic Mix)", reply_markup = keyboard)
    if message.text == "Into the A to Z":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn7 = types.KeyboardButton("Корейские альбомы")
        btn8 = types.KeyboardButton("Японские альбомы")
        btn9 = types.KeyboardButton("Назад")
        keyboard.add(btn7, btn8, btn9)
        image = open("atoz.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Трек-лист: 1.Pirate King (Japanese Ver.) 2.Say My Name (Japanese Ver.) 3.UTOPIA (Japanese Ver.)4.AURORA (Japanese Ver.) 5.WONDERLAND (Japanese Ver.) 6.Answer (Japanese Ver.) 7.Better 8.THANXX (Japanese Ver.) 9.INCEPTION (Japanese Ver.) 10.Still Here", reply_markup = keyboard)
    if message.text == "Дебют группы":
        bot.send_message(message.chat.id, "ATEEZ - мужская группа компании KQ Entertainment, состоящая из 8 мемберов. Они дебютировали 24 октрября 2018 года. Название группы является сокращением от «A TEEnager Z», что также означает «A to Z», то есть это группа подростков, которая стремится сделать все возможное")
    if message.text == "Фандом":
        bot.send_message(message.chat.id, "ATINY — официальное название фандома ATEEZ . Название было объявлено ATEEZ на V Live 17 ноября 2018 года. ATINY - это сокращение от «ATEEZ и destiny(судьба)”, что означает будущее ATEEZ вместе с ATINY")
    if message.text == "Назад":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn1 = types.KeyboardButton("О группе")
        btn2 = types.KeyboardButton("Дискография")
        keyboard.add(btn1, btn2)
        bot.send_message(message.chat.id, "Вы вернулись в главное меню", reply_markup = keyboard)
    if message.text == "Состав группы":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn40 = types.KeyboardButton("Ким Хонджун")
        btn41 = types.KeyboardButton("Пак Сонхва")
        btn42 = types.KeyboardButton("Чон Юнхо")
        btn43 = types.KeyboardButton("Кан Ёсан")
        btn44 = types.KeyboardButton("Чхве Сан")
        btn45 = types.KeyboardButton("Сон Минги")
        btn46 = types.KeyboardButton("Чон Уён")
        btn47 = types.KeyboardButton("Чхве Чонхо")
        keyboard.add(btn40, btn41, btn42, btn43, btn44, btn45,btn46, btn47)
        bot.send_message(message.chat.id, "Выберите участника", reply_markup = keyboard)
    if message.text == "Ким Хонджун":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Hongjoong.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Ким Хонджун \n— Позиции в группе: лидер, ведущий рэпер, композитор  \n— Дата рождения: 7 ноября 1998 \n— Место рождения: Анян, Кёнгидо, Южная Корея \n— Группа крови: В \n— Рост: 172 см \n— MBTI: INFP", reply_markup = keyboard)
    if message.text == "Пак Сонхва":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Seonghwa.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Пак Сонхва \n— Позиции в группе: саб-рэпер, саб-вокалист, вижуал  \n— Дата рождения: 3 апреля 1998 \n— Место рождения: Чинджу, Южная Корея \n— Группа крови: 0 \n— Рост: 178 см \n— MBTI: ENFJ-T", reply_markup = keyboard)
    if message.text == "Чон Юнхо":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Yunho.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Чон Юнхо \n— Позиции в группе: главный танцор, саб-вокалист \n— Дата рождения: 23 марта 1999 \n— Место рождения: Кванджу, Южная Корея  \n— Группа крови: А \n— Рост: 185 см \n— MBTI: ENFJ", reply_markup = keyboard)
    if message.text == "Кан Ёсан":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Yeosang.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Кан Ёсан \n— Позиции в группе: саб-вокалист, ведущий танцор, вижуал \n— Дата рождения: 15 июня 1999 \n— Место рождения: Инчхон, Южная Корея \n— Группа крови: А \n— Рост: 174 см \n— MBTI: ISFP-T", reply_markup = keyboard)
    if message.text == "Чхве Сан":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("San.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Чхве Сан \n— Позиции в группе: саб-вокалист, ведущий танцор \n— Дата рождения: 10 июля 1999 \n— Место рождения: Намхэ, Кёнсан-Намдо, Южная Корея  \n— Группа крови: B \n— Рост: 175,5 см \n— MBTI: INFP", reply_markup = keyboard)
    if message.text == "Сон Минги":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Mingi.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Сон Минги \n— Позиции в группе: главный рэпер, ведущий танцор, саб-вокалист  \n— Дата рождения: 9 августа 1999 \n— Место рождения: Инчхон, Южная Корея \n— Группа крови: B \n— Рост: 183 см \n— MBTI: ENTP", reply_markup = keyboard)
    if message.text == "Чон Уён":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Wooyoung.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Чон Уён \n— Позиции в группе: главный танцор, саб-вокалист, вижуал  \n— Дата рождения: 26 ноября 1999 \n— Место рождения: Чинджу, Южная Корея \n— Группа крови: A \n— Рост: 173 см \n— MBTI: ESFJ", reply_markup = keyboard)  
    if message.text == "Чхве Чонхо":
        keyboard = types.ReplyKeyboardMarkup(resize_keyboard = True)
        btn3 = types.KeyboardButton("Состав группы")
        btn4 = types.KeyboardButton("Дебют группы")
        btn5 = types.KeyboardButton("Фандом")
        btn6 = types.KeyboardButton("Назад")
        keyboard.add(btn3, btn4, btn5, btn6)
        image = open("Jongho.jpg", "rb")
        bot.send_photo(message.chat.id, image)
        bot.send_message(message.chat.id, "Чхве Чонхо \n— Позиции в группе: главный вокалист, макнэ  \n— Дата рождения: 12 октября 2000 \n— Место рождения: Сеул, Южная Корея \n— Группа крови: 0 \n— Рост: 176 см \n— MBTI: ISFP-T", reply_markup = keyboard)
                        




bot.polling(non_stop=True)